name: flutter_sketchpad
description: A Flutter package for adding text, drawings, and highlighter annotations to any widget.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lucide: ^1.6.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  freezed: ^2.5.8
  json_serializable: ^6.7.1

flutter: 